# This is a config for E2B sandbox template.
# You can use template ID (qqfrceifo55bgrxne3l0) or template name (maxi-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("maxi-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("maxi-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('maxi-nextjs-test')

team_id = "633a95c7-a673-4e9a-a2a2-2dadf28c6ae4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "g0-expo-app-v1"
template_id = "ncrohc4ieijqoq8ag5by"